src/Entity/EmployeePosts.php
<?php

namespace App\Entity;

use App\Repository\EmployeePostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeePostsRepository::class)]
class EmployeePosts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 90)]
    private ?string $name_post = null;

    #[ORM\OneToMany(mappedBy: 'fk_id_employeePost', targetEntity: Employee::class)]
    private Collection $employees;

    public function __construct()
    {
        $this->employees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNamePost(): ?string
    {
        return $this->name_post;
    }

    public function setNamePost(string $name_post): static
    {
        $this->name_post = $name_post;

        return $this;
    }

    /**
     * @return Collection<int, Employee>
     */
    public function getEmployees(): Collection
    {
        return $this->employees;
    }

    public function addEmployee(Employee $employee): static
    {
        if (!$this->employees->contains($employee)) {
            $this->employees->add($employee);
            $employee->setFkIdEmployeePost($this);
        }

        return $this;
    }

    public function removeEmployee(Employee $employee): static
    {
        if ($this->employees->removeElement($employee)) {
            // set the owning side to null (unless already changed)
            if ($employee->getFkIdEmployeePost() === $this) {
                $employee->setFkIdEmployeePost(null);
            }
        }

        return $this;
    }
}

src/Form/EmployeePostsType.php
<?php

namespace App\Form;

use App\Entity\EmployeePosts;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeePostsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_post', null, [
                "label" => "Название должности ",
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => EmployeePosts::class,
        ]);
    }
}

src/Controller/EmployeePostsController.php
<?php

namespace App\Controller;

use App\Entity\EmployeePosts;
use App\Form\EmployeePostsType;
use App\Repository\EmployeePostsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/employee_posts')]
class EmployeePostsController extends AbstractController
{
    #[Route('/', name: 'app_employee_posts_index', methods: ['GET'])]
    public function index(EmployeePostsRepository $employeePostsRepository): Response
    {
        return $this->render('employee_posts/index.html.twig', [
            'employee_posts' => $employeePostsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_employee_posts_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $employeePost = new EmployeePosts();
        $form = $this->createForm(EmployeePostsType::class, $employeePost);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($employeePost);
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee_posts/new.html.twig', [
            'employee_post' => $employeePost,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_posts_show', methods: ['GET'])]
    public function show(EmployeePosts $employeePost): Response
    {
        return $this->render('employee_posts/show.html.twig', [
            'employee_post' => $employeePost,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_employee_posts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, EmployeePosts $employeePost, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EmployeePostsType::class, $employeePost);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_employee_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('employee_posts/edit.html.twig', [
            'employee_post' => $employeePost,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_employee_posts_delete', methods: ['POST'])]
    public function delete(Request $request, EmployeePosts $employeePost, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$employeePost->getId(), $request->request->get('_token'))) {
            $entityManager->remove($employeePost);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_employee_posts_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/employee_posts/_delete_form.html.twig
<form method="post" action="{{ path('app_employee_posts_delete', {'id': employee_post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee_post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/employee_posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit EmployeePosts{% endblock %}

{% block body %}
    <h1>Edit EmployeePosts</h1>

    {{ include('employee_posts/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_employee_posts_index') }}">back to list</a>

    {{ include('employee_posts/_delete_form.html.twig') }}
{% endblock %}

templates/employee_posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Список должностей{% endblock %}

{% block body %}
    <style> a { text-decoration: none; } </style>
    <h1>Список должностей</h1>

    <table class="table">
        <thead>
            <tr>
                <th>№</th>
                <th>Наименование должности</th>
                <th>Возможные действия</th>
            </tr>
        </thead>
        <tbody>
        {% for employee_post in employee_posts %}
            <tr>
                <td>{{ employee_post.id }}</td>
                <td>{{ employee_post.namePost }}</td>
                <td>
                    <a href="{{ path('app_employee_posts_show', {'id': employee_post.id}) }}">Показать</a>
                    <a href="{{ path('app_employee_posts_edit', {'id': employee_post.id}) }}">Редактировать</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">Записей не найдено</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_employee_posts_new') }}">Создать новую запись</a>
    <a href="{{ path('app_home_page') }}">Вернуться на главную</a>
{% endblock %}

templates/employee_posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Новая должность{% endblock %}

{% block body %}
    <h1>Создать новую должность</h1>

    {{ include('employee_posts/_form.html.twig') }}

    <a href="{{ path('app_employee_posts_index') }}">Вернуться к списку</a>
{% endblock %}

templates/employee_posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EmployeePosts{% endblock %}

{% block body %}
    <h1>EmployeePosts</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ employee_post.id }}</td>
            </tr>
            <tr>
                <th>Name_post</th>
                <td>{{ employee_post.namePost }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_employee_posts_index') }}">back to list</a>

    <a href="{{ path('app_employee_posts_edit', {'id': employee_post.id}) }}">edit</a>

    {{ include('employee_posts/_delete_form.html.twig') }}
{% endblock %}